# Generated by Django 2.2 on 2021-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0002_foodmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='status',
        ),
    ]
