# Generated by Django 2.2 on 2021-03-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_amount', models.IntegerField()),
                ('unit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.UnitModel')),
            ],
        ),
    ]
