# Generated by Django 2.2 on 2021-03-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('material', '0003_auto_20210316_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('import_date', models.DateTimeField(auto_now=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialModel')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.SupplierModel')),
            ],
        ),
        migrations.DeleteModel(
            name='UnitModel',
        ),
    ]
