# Generated by Django 2.2 on 2021-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20210317_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmaterialmodel',
            name='import_date',
            field=models.DateTimeField(),
        ),
    ]
