# Generated by Django 2.2 on 2021-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(default='', max_length=400)),
                ('supplier_phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
