# Generated by Django 2.2 on 2021-03-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='supplier_address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
